
env:
   global:
     - CONAN_REFERENCE: "bitprim-consensus/0.1"
     - CONAN_USERNAME: "bitprim"
     - CONAN_LOGIN_USERNAME: "dario-ramos"
     - CONAN_CHANNEL: "stable"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/bitprim/bitprim-consensus"

linux: &linux
   os: linux
   sudo: required
   language: cpp
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:

      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49

      - <<: *linux
        env: CONAN_GCC_VERSIONS=5.4 CONAN_DOCKER_IMAGE=lasote/conangcc54

      - <<: *linux
        env: CONAN_GCC_VERSIONS=6.3 CONAN_DOCKER_IMAGE=lasote/conangcc63

install:
  - cd ${TRAVIS_BUILD_DIR}
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - cd ${TRAVIS_BUILD_DIR}
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
